# Generated by Django 4.0.4 on 2022-06-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_number', models.IntegerField(max_length=20)),
                ('student_email', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('parents_number', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=20)),
                ('room_no', models.CharField(default='00', max_length=10)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
