# Generated by Django 4.0.4 on 2022-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_student_data_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student_data',
            name='parents_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='student_number',
            field=models.CharField(max_length=20),
        ),
    ]
