# Generated by Django 4.0.4 on 2022-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_student_pass_alter_student_data_parents_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='join_by',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
