# Generated by Django 4.0.4 on 2022-06-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_student_data_join_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_name', models.CharField(max_length=50)),
                ('username', models.CharField(default='123', max_length=50)),
                ('guard_number', models.CharField(max_length=20)),
                ('guard_email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('join_by', models.CharField(default=' ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guard_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
