# Generated by Django 4.0.4 on 2022-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_guard_data_guard_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('username', models.CharField(default='123', max_length=50)),
                ('admin_number', models.CharField(max_length=20)),
                ('admin_email', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('join_by', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
