# Generated by Django 4.0.4 on 2022-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_admin_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_by', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('input_date', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('out_time', models.CharField(max_length=20)),
                ('in_time', models.CharField(max_length=20)),
                ('status', models.CharField(default='IN', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='student_data',
            name='status',
            field=models.CharField(default='IN', max_length=10),
        ),
        migrations.AlterField(
            model_name='admin_pass',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guard_pass',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_pass',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
