# Generated by Django 4.0.4 on 2022-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_alter_gatepass_in_time_alter_gatepass_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='hex_code',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='in_time',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='out_time',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
