# Generated by Django 4.0.4 on 2022-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0014_gatepass_in_date_gatepass_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='pass_status',
            field=models.CharField(default='ON', max_length=20),
        ),
    ]
