# Generated by Django 4.0.4 on 2022-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0016_alter_gatepass_in_date_alter_gatepass_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='my_check',
            field=models.CharField(default='yes', max_length=10),
        ),
    ]
