# Generated by Django 4.0.4 on 2022-07-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0018_remove_gatepass_my_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='pass_status',
        ),
    ]
