# Generated by Django 4.0.4 on 2022-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0019_remove_gatepass_pass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='entry_scan_by',
            field=models.CharField(default='not-set', max_length=50),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='outing_scan_by',
            field=models.CharField(default='not-set', max_length=50),
        ),
    ]
