# Generated by Django 4.0.6 on 2022-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0020_gatepass_entry_scan_by_gatepass_outing_scan_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='in_time',
            field=models.CharField(default='not-set', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='out_time',
            field=models.CharField(default='not-set', max_length=20, null=True),
        ),
    ]
